spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanqc
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
ok:
  http:
    connect-timeout: 30 # 连接超时时间，单位通常为秒
    read-timeout: 30 # 读取超时时间，单位通常为秒
    write-timeout: 30 # 写入超时时间，单位通常为秒
    max-idle-connections: 200 # 连接池中整体的空闲连接的最大数量
    keep-alive-duration: 300 # 连接空闲时间最多为多少秒

wenxin:
  apiKey: S5G5rBnjOVwGFwqIVUpKMguU
  secretKey: P4hCL0vZNT94mg1e9Uh1gBQMzzJHxskj
  accessTokenUrl: https://aip.baidubce.com/oauth/2.0/token
  ERNIE_Bot:
    URL: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-speed-128k  #改成你用的
